//
//  Endpoints.swift
//  TeachME
//
//  Created by TumbaDev on 13.03.25.
//

import Foundation

struct Endpoints {
    // MARK: NGROK uses a new autogenerated url
    static let baseURL: String = "https://28ca-2a01-5a8-469-b79e-c87a-e664-349a-6cf0.ngrok-free.app/"
    static let authURL: String = "\(baseURL)teach-me/"
    static let lessonTypesURL: String = "\(authURL)lesson-types/"
    static let rolesURL: String = "\(authURL)roles/"
    static let fetchAllRolesURL: String = "\(baseURL)roles"
    static let lessonsURL: String = "\(authURL)lessons/"
    static let usersURL: String = "\(authURL)users/"
}
