//
//  Endpoints.swift
//  TeachME
//
//  Created by TumbaDev on 13.03.25.
//

import Foundation

struct Endpoints {
    // MARK: NGROK uses a new autogenerated url
    static let baseURL: String = "https://7e48-2a01-5a8-303-389a-2d76-a6e5-f00e-a9f8.ngrok-free.app/"
    static let authURL: String = "\(baseURL)teach-me/"
    static let lessonTypesURL: String = "\(authURL)lesson-types/"
    static let rolesURL: String = "\(authURL)roles/"
    static let fetchAllRolesURL: String = "\(baseURL)roles"
    static let lessonsURL: String = "\(authURL)lessons/"
    static let usersURL: String = "\(authURL)users/"
}
